"""Standalone mock "valuation vendor" feed — stands in for an MLS/valuation-vendor system a
bank's core platform would pull property characteristics from over an API. Deliberately its
own tiny FastAPI app (not a module inside backend/app/) so "meeting data where it lives" is a
literal separate service with its own process/port/deploy, not an in-process shortcut.

Serves records_seed.json (generated by scripts/generate_ingestion_sources.py from a slice of
the Ames Housing dataset — see that script for the zero-scrape provenance note) as a paginated
JSON feed, the shape a real vendor API would take.
"""
import json
from pathlib import Path
from typing import Optional

from fastapi import FastAPI, Query

SEED_PATH = Path(__file__).resolve().parent / "records_seed.json"

app = FastAPI(title="Mock Valuation Vendor API")


def _load_records() -> list[dict]:
    if not SEED_PATH.exists():
        return []
    return json.loads(SEED_PATH.read_text())


@app.get("/health")
def health():
    return {"status": "ok", "records_available": len(_load_records())}


@app.get("/records")
def list_records(
    page: int = Query(1, ge=1),
    page_size: int = Query(100, ge=1, le=500),
    since: Optional[str] = Query(None, description="ISO timestamp — only records updated at/after this"),
):
    """Paginated JSON feed, the shape a real valuation-vendor/MLS-type API would expose.
    `since` filters on each record's own `last_updated` timestamp (set at seed time), letting
    a caller do an incremental pull instead of always re-fetching everything."""
    records = _load_records()
    if since:
        records = [r for r in records if r.get("last_updated", "") >= since]
    total = len(records)
    start = (page - 1) * page_size
    page_records = records[start:start + page_size]
    return {
        "page": page,
        "page_size": page_size,
        "total": total,
        "has_more": start + page_size < total,
        "records": page_records,
    }
