import React from 'react'
import { api } from '../api.js'

export default function DataProfile() {
  return (
    <div className="space-y-4">
      <div className="card p-6">
        <div className="label">Data Quality</div>
        <h1 className="text-2xl font-semibold mt-1">Training Data Profile</h1>
        <p className="text-sm text-inkmute mt-3 max-w-3xl leading-relaxed">
          Per-feature distributions, missingness, and summary statistics over the Ames
          training data the AVM models are fit on — generated by{' '}
          <a href="https://github.com/ydataai/ydata-profiling" target="_blank" rel="noopener noreferrer"
            className="text-teal hover:underline">ydata-profiling</a> and baked into this
          build. Reflects the source data as of this deploy, not live portfolio edits.
        </p>
        <a href={api.dataProfileReportUrl} target="_blank" rel="noopener noreferrer"
          className="inline-block mt-4 text-sm text-teal hover:underline">
          Open report in a new tab ↗
        </a>
      </div>

      <div className="card p-2">
        <iframe src={api.dataProfileReportUrl} title="Training data profile report"
          className="w-full border border-line rounded-sm" style={{ height: '80vh' }} />
      </div>
    </div>
  )
}
